### ISSUE TITLE
Missing files for visualization gallery task

### ISSUE THREAD

**Issue by nhintruong** [tdhock/species-variable-selection#1]
@tdhock I am trying to run the [Table Mountain Pine ](https://github.com/tdhock/species-variable-selection/blob/master/figure-batchtools-expired.R) source code, which required files named "registry-expired" and the directory "data/" (referenced in the line: spp.csv.vec <- normalizePath(Sys.glob(""data/*"")) ). However, I can't find these files in the repository. 

Could you please recheck the files or let me know if there is anywhere else I can find the required files? Thank you very much for your guidance

**Comment by tdhock** [comment]
I'm not sure these files are publicly available, so this should be added to list of viz which can not be ported

**Comment by tdhock** [comment]
actually these have already been ported
![image](https://github.com/tdhock/species-variable-selection/assets/932850/645fb8b5-e799-476c-acf4-6fb2b0b3803a)

**Comment by nhintruong** [comment]
> actually these have already been ported ![image](https://private-user-images.githubusercontent.com/932850/342524515-645fb8b5-e799-476c-acf4-6fb2b0b3803a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODgwOTMsIm5iZiI6MTcxOTI4Nzc5MywicGF0aCI6Ii85MzI4NTAvMzQyNTI0NTE1LTY0NWZiOGI1LWU3OTktNDc2Yy1hY2Y0LTZmYjJiMGIzODAzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwMzU2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTI3ZjRkZDZhMjhjOTlmYjM4N2Q3NzVmYzc2OTIxZGZmNjE2ZTc1YzkwNGY2MzRjZWQ3NDk0Njg3ZjM1OTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8io9ibtVMgcnO3fBO300xKS4CUn2ArikhHdEAFrZ704)

I've noticed the similarity between the photo and the Table Mountain Pine visualization. However, I found a difference in the "earth model variable selection" column (it did not appear in the NAU rcdata animint gallery), so I've wondered about porting it again.  Thanks to your feedback, I'll omit this from the porting process. 

Given that this visualization has already been ported, it seems unnecessary to include it in the list of non-portable visualizations. Is my understanding correct?

**Comment by tdhock** [comment]
ok
